package com.py2c.week.ui.strings

import com.py2c.week.data.WrongSource

@Suppress("TooManyFunctions")
object StringsEn : AppStrings {
    override val brandName = "C Week"
    override val brandSubtitle = "C一周通"
    override val tagline = "Seven days from zero to implementing Dijkstra in C"

    override val navHome = "This week"
    override val navLabs = "Labs"
    override val navWrongs = "Wrong book"
    override val navGlossary = "Glossary"

    override val back = "Back"
    override val cancel = "Cancel"
    override val clear = "Clear"
    override val reset = "Reset"
    override val passed = "Passed"
    override val notPassed = "Not passed"
    override val complete = "Complete"
    override val incomplete = "Incomplete"
    override val lessonDone = "Done"
    override val labPassed = "Lab passed"

    override val settingsTitle = "Settings & About"
    override val settingsLanguage = "Language"
    override val settingsTheme = "Appearance"
    override val settingsAbout = "About"
    override val languageSystem = "Follow system"
    override val languageZh = "中文"
    override val languageEn = "English"
    override val themeSystem = "Follow system"
    override val themeLight = "Light"
    override val themeDark = "Dark"

    override val aboutVersion = "Version"
    override val aboutLastUpdate = "Build time (local)"
    override val aboutSource = "Source repository"
    override val aboutOpenRepo = "Open on GitHub"
    override val aboutDescription = "C Week: a 7-day C intro with lessons, offline lab simulation, and quizzes."

    override fun homeProgressPercent(percent: Int) = "Week progress  $percent%"
    override val homeProgressBlurb =
        "Lessons use everyday analogies, then precise C. Each day: micro-lessons, lab, and quiz. Run real gcc in VS Code on your computer; the phone app teaches and simulates grading."
    override val homeWrongBookTitle = "Wrong book"
    override fun homeWrongBookBody(openWrongs: Int) = if (openWrongs == 0) {
        "Quiz and lab mistakes are grouped by day here. Tap to retry."
    } else {
        "$openWrongs to fix · Tap a day to retry; correct answers mark items resolved"
    }
    override val homeReportTitle = "Learning report"
    override fun homeReportBody(streak: Int, percent: Int) = "Streak $streak days · Overall $percent% · Share via system sheet"
    override val homeClearProgress = "Clear local progress"
    override val homeClearProgressTitle = "Clear progress?"
    override val homeClearProgressMessage = "Course content stays; only on-device completion records in DataStore are removed."
    override fun homeDayMeta(dayId: Int, minutes: Int) = "Day $dayId · $minutes min"
    override fun homeDayProgress(done: Int, total: Int) = "$done / $total items"
    override fun homeDayContentDescription(dayId: Int, title: String) = "Day $dayId $title"
    override fun overallProgressDescription(percent: Int) = "Overall progress $percent percent"

    override val calendarTitle = "Study calendar"
    override fun calendarStreak(streak: Int, litCount: Int) = "Streak $streak days · $litCount / 7 days lit"
    override fun calendarNudgeAllDone() = "All seven days lit — week complete. Re-run Dijkstra with gcc on your computer."
    override fun calendarNudgeNext(dayId: Int, title: String) = "One day at a time: next is Day $dayId «$title». Light all seven to graduate."
    override val calendarNudgeFinish = "Finish remaining labs and quizzes to fill the calendar."
    override val calendarWeekLabel = "This calendar week"
    override val calendarCheckInToday = "Check in today"
    override val calendarCheckedInToday = "Checked in today"
    override val calendarCheckInHintChecked = "Today is stamped. Completing a lesson, lab, or quiz also counts toward your streak."
    override val calendarCheckInHintUnchecked = "Tap to stamp today; any lesson, lab, or quiz also checks you in."
    override val calendarCellOn = "On"
    override val calendarCellOff = "Off"
    override fun calendarDayDone(dayId: Int) = "Day $dayId complete"
    override fun calendarDayNotDone(dayId: Int) = "Day $dayId incomplete"

    override val wrongBookTitle = "Wrong book"
    override val wrongBookIntro = "Wrong quiz answers and failed labs are saved here by day. Retry until all are correct."
    override fun wrongBookOpenCount(open: Int) = "$open to fix"
    override fun wrongBookResolvedCount(done: Int) = "$done resolved"
    override val wrongBookOpenReport = "Open learning report"
    override val wrongBookEmptyTitle = "Nothing to fix"
    override val wrongBookEmptyBody = "Take a quiz or lab. Mistakes appear here grouped by day."
    override fun wrongBookDayHeader(dayId: Int, title: String) = "Day $dayId · $title"
    override fun wrongBookDayResolved(dayId: Int) = "Day $dayId · resolved"
    override val wrongBookHideResolved = "Hide resolved"
    override fun wrongBookShowResolved(count: Int) = "Show resolved ($count)"
    override fun wrongSourceLabel(source: WrongSource) = if (source == WrongSource.QUIZ) "Quiz" else "Lab"
    override val wrongResolvedSuffix = " · resolved"
    override val wrongYourAnswer = "Your answer: "
    override val wrongCorrectAnswer = "Correct: "
    override val wrongRedoQuiz = "Tap to retry this question"
    override val wrongRedoLab = "Tap to reopen the lab"

    override val reportTitle = "Learning report"
    override fun reportStreak(streak: Int) = "Streak $streak days"
    override fun reportCheckins(checkinDays: Int, percent: Int) = "$checkinDays days with activity · Overall $percent%"
    override val reportQuizAccuracy = "Quiz accuracy"
    override val reportLabsPassed = "Labs passed"
    override val reportQuizNotTaken = "No quiz submitted"
    override fun reportQuizSubtitle(correct: Int, asked: Int) = "$correct/$asked"
    override fun reportOpenWrongs(count: Int) = "$count to fix"
    override val reportDayBreakdown = "Progress by day"
    override fun reportDayLine(dayId: Int, title: String) = "Day $dayId · $title"
    override fun reportDayDetail(percent: Int, done: Int, total: Int, quizPart: String, labPart: String) =
        "$percent% ($done/$total) · $quizPart · $labPart"
    override val reportQuizNotSubmitted = "Quiz not submitted"
    override fun reportQuizScore(score: Int, total: Int) = "Quiz $score/$total"
    override val reportLabDone = "Lab passed"
    override val reportLabNotDone = "Lab not passed"
    override val reportShare = "  Share report"
    override val reportShareHint = "Opens the system share sheet (WeChat, email, etc.). Only local progress; no account."
    override val reportShareChooser = "Share learning report"
    override fun reportShareSubject(brand: String) = "$brand learning report"

    override val labsListTitle = "Code labs"
    override val labsListIntro =
        "Each lab has multiple offline test cases with partial credit and categorized hints. Failures go to the wrong book. Compile with gcc/clang in VS Code on your computer."
    override fun labsListDay(dayId: Int, capstone: Boolean) =
        "Day $dayId${if (capstone) " · capstone" else ""}"
    override val labsCapstoneBadge = "Capstone"

    override val labTitle = "Lab"
    override val labCapstoneTitle = "Capstone"
    override fun labDayLabel(dayId: Int) = "Day $dayId"
    override fun labCompileHint(capstone: Boolean) =
        "On desktop: gcc ${if (capstone) "dijkstra.c -o dijkstra" else "lab.c -o lab"} -Wall. Below is the teaching simulator."
    override fun labTestCasesHeader(count: Int) = "Test cases ($count groups, not just one golden output)"
    override val labSimulatedInput = "Simulated input: "
    override val labExpected = "Expected: "
    override val labEditor = "Editor"
    override val labRunCheck = "Simulate run / check"
    override fun labHintsTitle(attempts: Int) = "Hints (attempt $attempts)"
    override val labExpectedOutput = "Expected output"
    override val labSolutionShown = "Reference solution shown"
    override val labRevealSolution = "Show reference solution"
    override fun labRevealAfterAttempts(remaining: Int) = "Try $remaining more time(s) to unlock solution"
    override val labReferenceSolution = "Reference solution"

    override fun labSimPassed() = "Simulation passed · 100%"
    override fun labSimPartial(score: Int) = "Partial pass · score $score%"
    override fun labSimFailed(score: Int) = "Simulation failed · score $score%"
    override fun labCasesProgress(passed: Int, total: Int) = "Cases $passed / $total"
    override fun labChecksProgress(passed: Int, total: Int) = "Structure checks $passed / $total"
    override val labSimStdout = "Simulated stdout:"
    override val labPartialHint = "Some cases passed; partial score by case count. Failures go to the wrong book; all cases must pass to complete the lab."
    override val labFailHint = "Multiple cases failed. Hints below cover common issues (headers, off-by-one, pointers, formulas, TODO stubs, BFS vs Dijkstra)."
    override fun labCasePassed(name: String) = "Case «$name» passed"
    override fun labCaseFailed(name: String) = "Case «$name» failed"
    override fun labCaseCompare(expected: String, actual: String) = "Expected $expected · got $actual"
    override val labNoOutput = "(no output)"
    override fun labCheckPassed(id: String) = "Check $id passed"
    override fun labCheckFailed(id: String, hint: String) = "Check $id: $hint"
    override fun labGradeHintTitle(title: String) = "Issue · $title"

    override val dijkstraBoardTitle = "Step through / path"
    override val dijkstraBoardUnlocked =
        "After passing checks, step through how Dijkstra fixes distances. Yellow edge = relax; teal = final shortest path."
    override val dijkstraBoardLocked =
        "Complete the relax loop and pass checks to play how dist goes from INF to 0 2 1 3 on 0→2→1→3."
    override fun dijkstraStep(step: Int, total: Int, caption: String) = "Step $step/$total · $caption"
    override fun dijkstraDistLine(dist: List<String>) = "dist = ${dist.joinToString(" ")}"
    override val dijkstraPrevStep = "Previous"
    override val dijkstraPlay = "Play"
    override val dijkstraPause = "Pause"
    override val dijkstraNextStep = "Next"
    override val dijkstraReplay = "Restart"
    override val dijkstraUnlockHint = "Pass the simulator check to unlock"
    override fun dijkstraCellLabel(node: Int) = "Node $node"

    override val dayLessons = "Lessons"
    override fun dayTodayFocus(focus: String) = "Today's focus: $focus"
    override fun dayCompleteBanner(dayId: Int) = "Day complete — lights Day $dayId on the home calendar"
    override fun dayIncompleteBanner(dayId: Int) = "Finish all lessons, lab, and quiz below to light D$dayId on the home calendar"
    override fun dayProgressDetail(lessonsDone: Int, lessonTotal: Int, labDone: Int, quizDone: Int) =
        "$lessonsDone/$lessonTotal lessons · $labDone/1 lab · $quizDone/1 quiz"
    override val dayCapstoneLab = "Capstone lab"
    override val dayTodayLab = "Today's lab"
    override fun dayQuizLabel(count: Int) = "Today's quiz · $count questions"
    override fun dayQuizSubmitted(score: Int, total: Int) = "Submitted · score $score/$total"
    override val dayQuizPending = "Submit to record progress"
    override fun dayTitle(dayId: Int) = "Day $dayId"

    override val quizTitle = "Quiz"
    override fun quizRedoTitle(dayId: Int) = "Wrong-book retry · Day $dayId"
    override val quizRedoIntro = "Only questions from your wrong book. All correct marks them resolved."
    override fun quizLastScore(score: Int, total: Int) = "Last score $score / $total. Retake to replace it."
    override fun quizScoreLine(score: Int, total: Int) = "Correct $score / $total"
    override val quizResultAllCorrectRedo = "All correct — removed from to-fix (still visible under resolved)."
    override val quizResultAllCorrect = "All correct — no wrong-answer details shown."
    override val quizResultPartialRedo = "Some still wrong. Correct ones resolve; others stay in the wrong book."
    override val quizResultPartial = "Wrong answers saved to the wrong book. Retry by day; details below."
    override val quizSubmitRedo = "Submit retry"
    override val quizSubmit = "Submit quiz"
    override fun quizSubmittedScore(score: Int, total: Int) = "Submitted · $score / $total"
    override val quizRetryRedo = "Practice again"
    override val quizRetry = "Retake quiz"
    override val quizVerdictCorrect = "Verdict: correct"
    override val quizVerdictWrong = "Verdict: wrong"
    override val quizCategory = "Category: "
    override val quizYouChose = "You chose: "
    override val quizWrongReason = "Why wrong: "
    override val quizCorrect = "Correct: "
    override val quizConceptFallback = "Concept"

    override fun lessonDayMeta(dayId: Int, minutes: Int) = "Day $dayId · $minutes min"
    override fun lessonCardSubtitle(minutes: Int, summary: String) = "$minutes min · $summary"
    override val lessonVideoMissing = "Device video not bundled; showing schematic instead."
    override val lessonViewSchematic = "View schematic"
    override val lessonMarkDoneReturn = "Marked done — back"
    override val lessonMarkDone = "Mark done & save progress"
    override val demoScreenTitle = "VS Code walkthrough"
    override fun vscodeDemoContentDescription(title: String) = "VS Code demo: $title"
    override val vscodeSpeedLabel = "Speed (default 0.75× to follow along)"
    override fun vscodeStepProgress(active: Int, total: Int) = "Steps highlighted ($active / $total)"
    override val vscodeExplainingNow = "Now · "

    override val glossaryTitle = "C glossary"
    override val glossaryIntro = "Pointers, stack/heap, toolchain terms — analogy first, then precise meaning."
    override val glossaryAll = "All"

    override fun memoryVizCaption(variant: String) = when (variant) {
        "pointer_basic" -> "Animation: p holds the address of x. Dereferencing *p follows the arrow to x."
        "array_decay" -> "Array a[3] decays to a pointer to a[0] in function parameters."
        "cstring" -> "\"hi\" is h, i, \\0 — three bytes. Missing \\0 makes %s read past the end."
        "heap" -> "Stack pointer p points to heap int. After free, the arrow must be invalid."
        else -> "Memory diagram"
    }

    override val memoryVizLegendVar = "Variable cell"
    override val memoryVizLegendPtr = "Pointer / address"
    override val memoryVizLegendData = "Data"

    override fun walkthroughStepLabel(index: Int, total: Int) = "Step ${index + 1} / $total"
    override val walkthroughNewFile = "+ New file"
    override val walkthroughFocus = "Current click / focus"

    override val errorContainerMissing = "AppContainer not provided"
}
