package com.py2c.week.ui.strings

import com.py2c.week.data.WrongSource

@Suppress("TooManyFunctions")
object StringsZh : AppStrings {
    override val brandName = "C一周通"
    override val brandSubtitle = "C Week"
    override val tagline = "7 天，从零基础走到能用 C 写出 Dijkstra 最短路"

    override val navHome = "本周课程"
    override val navLabs = "代码实验"
    override val navWrongs = "错题本"
    override val navGlossary = "词汇表"

    override val back = "返回"
    override val cancel = "取消"
    override val clear = "清除"
    override val reset = "重置"
    override val passed = "通过"
    override val notPassed = "未通过"
    override val complete = "已完成"
    override val incomplete = "未完成"
    override val lessonDone = "已学完"
    override val labPassed = "实验已通过"

    override val settingsTitle = "设置与关于"
    override val settingsLanguage = "语言"
    override val settingsTheme = "外观"
    override val settingsAbout = "关于"
    override val languageSystem = "跟随系统"
    override val languageZh = "中文"
    override val languageEn = "English"
    override val themeSystem = "跟随系统"
    override val themeLight = "浅色"
    override val themeDark = "深色"

    override val aboutVersion = "版本"
    override val aboutLastUpdate = "构建时间（本地时区）"
    override val aboutSource = "源码仓库"
    override val aboutOpenRepo = "在浏览器中打开 GitHub"
    override val aboutDescription = "C一周通：7 天 C 语言入门，含微课、离线实验模拟与测验。"

    override fun homeProgressPercent(percent: Int) = "一周进度  $percent%"
    override val homeProgressBlurb =
        "课文用生活场景打比方（门牌号、食谱、储物柜），再落到精确的 C。每天微课 + 实验 + 测验。真正的 gcc 在电脑 VS Code 里跑，手机上是讲解与模拟评测。"
    override val homeWrongBookTitle = "错题本"
    override fun homeWrongBookBody(openWrongs: Int) = if (openWrongs == 0) {
        "测验和实验的错题会按天列在这里，点进去重练。"
    } else {
        "待订正 $openWrongs 题 · 点按按天重练，做对即标记已订正"
    }
    override val homeReportTitle = "学习报告"
    override fun homeReportBody(streak: Int, percent: Int) = "连续打卡 $streak 天 · 总体 $percent% · 可系统分享"
    override val homeClearProgress = "清除本地进度"
    override val homeClearProgressTitle = "清除进度？"
    override val homeClearProgressMessage = "课程内容仍在，只删除本机 DataStore 里的完成记录。"
    override fun homeDayMeta(dayId: Int, minutes: Int) = "第 $dayId 天 · $minutes 分钟"
    override fun homeDayProgress(done: Int, total: Int) = "$done / $total 项"
    override fun homeDayContentDescription(dayId: Int, title: String) = "第${dayId}天 $title"
    override fun overallProgressDescription(percent: Int) = "总体完成 $percent 百分之"

    override val calendarTitle = "学习日历"
    override fun calendarStreak(streak: Int, litCount: Int) = "连续打卡 $streak 天 · 已点亮 $litCount / 7 关"
    override fun calendarNudgeAllDone() = "七关全亮，本周毕业。可以把 Dijkstra 再在电脑 gcc 里跑一遍。"
    override fun calendarNudgeNext(dayId: Int, title: String) = "一关一天：下一关是第 ${dayId} 天「$title」。点亮 7 格就毕业。"
    override val calendarNudgeFinish = "把剩下的实验和测验做完，整周格子就会亮满。"
    override val calendarWeekLabel = "本周日历（按真实日期）"
    override val calendarCheckInToday = "今日打卡"
    override val calendarCheckedInToday = "今日已打卡"
    override val calendarCheckInHintChecked = "今天的格子已经盖章。做完一关课文/实验/测验也会自动记入连续天数。"
    override val calendarCheckInHintUnchecked = "点一下给今天盖章；完成任意课文、实验或测验也会自动打卡。"
    override val calendarCellOn = "亮"
    override val calendarCellOff = "关"
    override fun calendarDayDone(dayId: Int) = "第${dayId}天已完成"
    override fun calendarDayNotDone(dayId: Int) = "第${dayId}天未完成"

    override val wrongBookTitle = "错题本"
    override val wrongBookIntro = "测验答错、实验未通过都会记在这里。按天查看，点进去重练；全部做对即标记已订正。"
    override fun wrongBookOpenCount(open: Int) = "待订正 $open 题"
    override fun wrongBookResolvedCount(done: Int) = "已订正 $done 题"
    override val wrongBookOpenReport = "打开学习报告"
    override val wrongBookEmptyTitle = "暂无待订正"
    override val wrongBookEmptyBody = "去做测验或实验。答错的题目会按第几天列在这里，方便回炉。"
    override fun wrongBookDayHeader(dayId: Int, title: String) = "第 $dayId 天 · $title"
    override fun wrongBookDayResolved(dayId: Int) = "第 $dayId 天 · 已订正"
    override val wrongBookHideResolved = "收起已订正"
    override fun wrongBookShowResolved(count: Int) = "查看已订正（$count）"
    override fun wrongSourceLabel(source: WrongSource) = if (source == WrongSource.QUIZ) "测验" else "实验"
    override val wrongResolvedSuffix = " · 已订正"
    override val wrongYourAnswer = "你的作答："
    override val wrongCorrectAnswer = "正确："
    override val wrongRedoQuiz = "点按重练这一题"
    override val wrongRedoLab = "点按回实验重跑模拟评测"

    override val reportTitle = "学习报告"
    override fun reportStreak(streak: Int) = "连续打卡 $streak 天"
    override fun reportShareStreakLine(streak: Int, checkinDays: Int) =
        "${reportStreak(streak)}（累计 $checkinDays 天有学习记录）"
    override fun reportCheckins(checkinDays: Int, percent: Int) = "累计 $checkinDays 天有学习记录 · 总体进度 $percent%"
    override val reportQuizAccuracy = "测验正确率"
    override val reportLabsPassed = "实验通过"
    override val reportQuizNotTaken = "还没交卷"
    override fun reportQuizSubtitle(correct: Int, asked: Int) = "$correct/$asked"
    override fun reportOpenWrongs(count: Int) = "待订正 $count 题"
    override val reportDayBreakdown = "分天完成度"
    override fun reportDayLine(dayId: Int, title: String) = "第 $dayId 天 · $title"
    override fun reportDayDetail(percent: Int, done: Int, total: Int, quizPart: String, labPart: String) =
        "$percent%（$done/$total） · $quizPart · $labPart"
    override val reportQuizNotSubmitted = "测验未交"
    override fun reportQuizScore(score: Int, total: Int) = "测验 $score/$total"
    override val reportLabDone = "实验已过"
    override val reportLabNotDone = "实验未过"
    override val reportShare = "  分享报告"
    override val reportShareHint = "会打开系统分享面板，可发到微信、邮件或其他应用。内容只含本机进度，不含账号。"
    override val reportShareChooser = "分享学习报告"
    override fun reportShareSubject(brand: String) = "${brand}学习报告"

    override val labsListTitle = "代码实验"
    override val labsListIntro =
        "每题有多组离线用例：会显示通过组数和部分得分，并按类别给出中文错因（缺头文件、差一、指针、公式、TODO 空壳等）。未通过会记入错题本。真实编译请在电脑 VS Code 使用 gcc/clang。"
    override fun labsListDay(dayId: Int, capstone: Boolean) =
        "第 $dayId 天${if (capstone) " · 大作业" else ""}"
    override val labsCapstoneBadge = "大作业"

    override val labTitle = "实验"
    override val labCapstoneTitle = "大作业"
    override fun labDayLabel(dayId: Int) = "第 $dayId 天"
    override fun labCompileHint(capstone: Boolean) =
        "真实编译在电脑：gcc ${if (capstone) "dijkstra.c -o dijkstra" else "lab.c -o lab"} -Wall。下面是教学模拟器。"
    override fun labTestCasesHeader(count: Int) = "测试用例（共 $count 组，不只对照一条黄金输出）"
    override val labSimulatedInput = "模拟输入："
    override val labExpected = "期望："
    override val labEditor = "编辑器"
    override val labRunCheck = "模拟运行 / 检查"
    override fun labHintsTitle(attempts: Int) = "提示（尝试 $attempts 次）"
    override val labExpectedOutput = "期望输出"
    override val labSolutionShown = "参考答案已展开"
    override val labRevealSolution = "揭晓参考答案"
    override fun labRevealAfterAttempts(remaining: Int) = "再试 $remaining 次后可看答案"
    override val labReferenceSolution = "参考实现"

    override fun labSimPassed() = "模拟运行通过 · 100%"
    override fun labSimPartial(score: Int) = "部分通过 · 得分 $score%"
    override fun labSimFailed(score: Int) = "模拟运行未通过 · 得分 $score%"
    override fun labCasesProgress(passed: Int, total: Int) = "用例 $passed / $total"
    override fun labChecksProgress(passed: Int, total: Int) = "结构检查 $passed / $total"
    override val labSimStdout = "模拟 stdout:"
    override val labPartialHint = "有的用例过了、有的没过，按组数给部分分。未通过的会记入错题本；全部通过才算完成实验。"
    override val labFailHint = "对照多组用例失败。下面按类别标出错因（缺头文件、差一、指针、公式、TODO 空壳、BFS/Dijkstra 搞混等）。"
    override fun labCasePassed(name: String) = "用例「$name」通过"
    override fun labCaseFailed(name: String) = "用例「$name」未通过"
    override fun labCaseCompare(expected: String, actual: String) = "期望 $expected · 模拟 $actual"
    override val labNoOutput = "（无输出）"
    override fun labCheckPassed(id: String) = "检查 $id 通过"
    override fun labCheckFailed(id: String, hint: String) = "检查 $id：$hint"
    override fun labGradeHintTitle(title: String) = "错因 · $title"

    override val dijkstraBoardTitle = "走格子 / 看路径"
    override val dijkstraBoardUnlocked =
        "通过检查后可以逐步看 Dijkstra 怎样把距离钉死。高亮边是当前松弛，青边是最终最短路。"
    override val dijkstraBoardLocked =
        "补全松弛并通过检查后，这里会播放 0→2→1→3 怎么把 dist 从 INF 写成 0 2 1 3。"
    override fun dijkstraStep(step: Int, total: Int, caption: String) = "步骤 $step/$total　$caption"
    override fun dijkstraDistLine(dist: List<String>) = "dist = ${dist.joinToString(" ")}"
    override val dijkstraPrevStep = "上一步"
    override val dijkstraPlay = "播放"
    override val dijkstraPause = "暂停"
    override val dijkstraNextStep = "下一步"
    override val dijkstraReplay = "从头"
    override val dijkstraUnlockHint = "先通过模拟检查，再解锁走格子"
    override fun dijkstraCellLabel(node: Int) = "格 $node"

    override val dayLessons = "微课"
    override fun dayTodayFocus(focus: String) = "今日重点：$focus"
    override fun dayCompleteBanner(dayId: Int) = "本关已点亮，计入学习日历第 $dayId 天"
    override fun dayIncompleteBanner(dayId: Int) = "一关一天：做完下面全部微课、实验和测验，首页日历会点亮 D$dayId"
    override fun dayProgressDetail(lessonsDone: Int, lessonTotal: Int, labDone: Int, quizDone: Int) =
        "进度 $lessonsDone/$lessonTotal 课 · $labDone/1 实验 · $quizDone/1 测验"
    override val dayCapstoneLab = "大作业实验"
    override val dayTodayLab = "今日实验"
    override fun dayQuizLabel(count: Int) = "今日测验 · $count 题"
    override fun dayQuizSubmitted(score: Int, total: Int) = "已提交，得分 $score/$total"
    override val dayQuizPending = "提交后记入进度"
    override fun dayTitle(dayId: Int) = "第 $dayId 天"

    override val quizTitle = "测验"
    override fun quizRedoTitle(dayId: Int) = "错题重练 · 第 $dayId 天"
    override val quizRedoIntro = "只重练错题本里的题目。全部选对会标记为已订正。"
    override fun quizLastScore(score: Int, total: Int) = "上次得分 $score / $total。可以重做，新分数会覆盖。"
    override fun quizScoreLine(score: Int, total: Int) = "答对 $score / $total"
    override val quizResultAllCorrectRedo = "全部正确，已从待订正列表清掉（仍可在「已订正」里看到）。"
    override val quizResultAllCorrect = "全部正确。错因栏不会出现——你已经选对了。"
    override val quizResultPartialRedo = "还有错题。选对的会立刻标记已订正，错的会留在错题本。"
    override val quizResultPartial = "错题已记入错题本。可到「错题本」按天重练；下面仍有「判断 / 你选了 / 错因 / 正确」。"
    override val quizSubmitRedo = "提交重练"
    override val quizSubmit = "提交测验"
    override fun quizSubmittedScore(score: Int, total: Int) = "已提交 · $score / $total"
    override val quizRetryRedo = "再练一次"
    override val quizRetry = "再测一次"
    override val quizVerdictCorrect = "判断：正确"
    override val quizVerdictWrong = "判断：错误"
    override val quizCategory = "类别："
    override val quizYouChose = "你选了："
    override val quizWrongReason = "错因："
    override val quizCorrect = "正确："
    override val quizConceptFallback = "概念"

    override fun lessonDayMeta(dayId: Int, minutes: Int) = "第 $dayId 天 · $minutes 分钟"
    override fun lessonCardSubtitle(minutes: Int, summary: String) = "$minutes 分钟 · $summary"
    override val lessonVideoMissing = "实机录像未打包，暂时使用示意图。"
    override val lessonViewSchematic = "查看示意图"
    override val lessonMarkDoneReturn = "已标记学完，返回"
    override val lessonMarkDone = "学完了，记入进度"
    override val demoScreenTitle = "VS Code 实机演示"
    override fun vscodeDemoContentDescription(title: String) = "VS Code 实机演示：$title"
    override val vscodeSpeedLabel = "语速（默认 0.75×，便于看清操作）"
    override fun vscodeStepProgress(active: Int, total: Int) = "操作清单随进度高亮（第 ${active + 1} / $total 步）"
    override val vscodeExplainingNow = "正在讲解 · "

    override val glossaryTitle = "C 词汇表"
    override val glossaryIntro = "指针、栈堆、工具链等词。每条先给生活类比，再写精确含义。"
    override val glossaryAll = "全部"

    override fun memoryVizCaption(variant: String) = when (variant) {
        "pointer_basic" -> "动画：p 里存的是 x 的地址。解引用 *p 就是顺着箭头改 x。"
        "array_decay" -> "数组 a[3] 在函数参数里变成指向 a[0] 的指针。"
        "cstring" -> "\"hi\" 实际是 h i \\0 三格。少了最后一格，%s 就会越界。"
        "heap" -> "栈上的 p 指向堆上的 int。free 后箭头必须作废。"
        else -> "内存示意"
    }

    override val memoryVizLegendVar = "变量格子"
    override val memoryVizLegendPtr = "指针 / 地址"
    override val memoryVizLegendData = "数据"

    override fun walkthroughStepLabel(index: Int, total: Int) = "步骤 ${index + 1} / $total"
    override val walkthroughNewFile = "+ 新建文件"
    override val walkthroughFocus = "当前点击/焦点"

    override val errorContainerMissing = "AppContainer 未提供"
}
